#!/usr/bin/env bash
# Regenerate the two lock files from requirements/*.in:
#   requirements.txt      runtime lock shipped in every release (contract v1)
#   requirements-dev.txt  runtime + development/CI tooling
#
# Universal resolution covers the supported server interpreters (Python
# 3.10-3.12) with environment markers, and every distribution file hash is
# recorded so pip can verify downloads (--require-hashes) on the VM and in CI.
#
# Usage: scripts/lock-requirements.sh            keep locked versions, refresh hashes/markers
#        UPGRADE=1 scripts/lock-requirements.sh  move to the newest allowed releases
# Needs `uv` (pinned in requirements/dev.in).
set -euo pipefail
cd "$(dirname "$0")/.."
command -v uv >/dev/null 2>&1 || { echo "uv not found; install it first (see requirements/dev.in for the pinned version)" >&2; exit 1; }

compile() {
  # compile <input> <output> <header-text>
  #
  # Compiling straight into the existing output keeps the versions already
  # locked (uv treats them as preferences), so re-running only changes the
  # lock when an .in file changed. Pass UPGRADE=1 to move every package to
  # its newest allowed release deliberately.
  local input="$1" output="$2" header="$3" tmp
  local -a extra=()
  [[ "${UPGRADE:-0}" == "1" ]] && extra+=(--upgrade)
  uv pip compile --universal --python-version 3.10 --generate-hashes --no-header \
    --annotation-style line "${extra[@]+"${extra[@]}"}" "${input}" -o "${output}" >/dev/null
  tmp="$(mktemp)"
  { printf '%s\n' "${header}"; cat "${output}"; } > "${tmp}"
  mv -- "${tmp}" "${output}"
  echo "${output} regenerated ($(grep -cE '^[a-zA-Z0-9_.-]+==' "${output}") packages)."
}

compile requirements/runtime.in requirements.txt \
'# lightsail-demo runtime dependency lock (deployment contract v1: "requirements.txt").
#
# Generated by scripts/lock-requirements.sh from requirements/runtime.in with
# uv (universal resolution for Python 3.10-3.12, all distribution hashes).
# Installed on the server with:
#   .venv/bin/python -m pip install --require-virtualenv --require-hashes --no-deps -r requirements.txt
# Do not edit by hand; edit requirements/runtime.in and re-run the script.'

compile requirements/dev.in requirements-dev.txt \
'# lightsail-demo development/CI lock: runtime + tooling. Never installed on the server.
#
# Generated by scripts/lock-requirements.sh from requirements/dev.in with uv
# (universal resolution for Python 3.10-3.12, all distribution hashes).
# Install with: python -m pip install --require-hashes -r requirements-dev.txt
# Do not edit by hand; edit requirements/dev.in and re-run the script.'
